### ISSUE TITLE
Doesn't work in GNOME 3.32

### ISSUE THREAD

**Issue by AlexWayfer** [ifl0w/RandomWallpaperGnome3#56]
GNOME 3.32 has been released: https://www.gnome.org/news/2019/03/gnome-3-32-released/

Arch Linux.

![Screenshot from 2019-03-16 12-57-14](https://user-images.githubusercontent.com/6510020/54473644-8e316800-47eb-11e9-8f51-5905917bac33.png)

```
Extension "randomwallpaper@iflow.space" had error: TypeError: this._construct is not a function
```

**Comment by fikrimi23** [comment]
I can confirm the issue, and so far, only DashToDock seems has fix it https://github.com/micheleg/dash-to-dock/issues/877, I tried myself so far, already change constructor, and replaced `: function ()`, but I can't undertand the `Lang.Class` part

**Comment by ifl0w** [comment]
I rewrote every class with the ES6 class syntax as this resolves the problem but I need to do some testing if older gnome-shell versions (3.22) still work.
I'll upload the updated version as soon as possible to extensions.gnome.org. 

Thanks for the report!

**Comment by ifl0w** [comment]
Sadly I have to drop the support for all gnome-shell versions < 3.28 with this update since those versions do not support the required class syntax.

Older versions will not receive any updates from now on.

**Comment by AlexWayfer** [comment]
@ifl0w I think, it's OK. The world is moving on. :wink:
